Deploy with ansible
jmmourier/laughing-couscous pull request #53
Opened 2021-01-26 17:09 UTC by capozzid

Everything is on the [wiki](https://github.com/jmmourier/laughing-couscous/wiki/%5BAnsible%5D-Automatic-deployment)

2021-01-27 18:48 UTC, jmmourier requested changes
The PR is great and we seems to have everything for the next step. 
Let's try that on Friday and we will discuss the main app issue as well.

2021-01-27 18:48 UTC, jmmourier commented on tools/docker/Dockerfile
> -    libboost-all-dev
Why boost is still here ?

2021-01-27 18:48 UTC, jmmourier commented on ansible/playbook/roles/push_back/tasks/main.yml
> +    src: "{{ PROJECT_PATH }}/build/application_test_gui/application_test_gui_exe"
I'm not comfortable with mixing a test app and the main "back" of the application.
For now this could work, but we seen need to use the main app instead, of separate the roles

2021-01-27 18:49 UTC, jmmourier commented on tools/docker/Dockerfile
> -    libboost-all-dev
(that's actually the line below on the review. the one that add 
`libboost-all-dev \`

2021-01-29 13:34 UTC, capozzid commented on ansible/playbook/roles/push_back/tasks/main.yml
> +    src: "{{ PROJECT_PATH }}/build/application_test_gui/application_test_gui_exe"
yes and don't worry this will become an option, but first will rename the app into separate ones. Something like:

- application
- application_gui
- application_gui_simulated

2021-01-31 17:58 UTC, jmmourier commented on ansible/playbook/roles/push_back/tasks/main.yml
> +    src: "{{ PROJECT_PATH }}/build/application_test_gui/application_test_gui_exe"
If it's an application it shall be in the application folder, and I suppose we can remove the "word application" from the application

2021-01-31 18:00 UTC, capozzid commented on ansible/playbook/roles/push_back/tasks/main.yml
> +    src: "{{ PROJECT_PATH }}/build/application_test_gui/application_test_gui_exe"
I have a branch for that already that moves the application_test_gui into applications folder see: [this branche](https://github.com/jmmourier/laughing-couscous/tree/couscous_manager_module). I'll create a PR once ansible is merged

2021-01-31 18:07 UTC, capozzid commented on ansible/playbook/roles/push_back/tasks/main.yml
> +    src: "{{ PROJECT_PATH }}/build/application_test_gui/application_test_gui_exe"
> If it's an application it shall be in the application folder, and I suppose we can remove the "word application" from the application

if you want to remove the word "application" that's fine for me, we just have to find a name for the app that will be the final release meaning -> no GUI and no simulator

2021-01-31 19:02 UTC, jmmourier commented
I will test the branch again later. 
the deployement was mostly working for me but the back. 

Any way we can move the ansible folder to tools please ? (at the root we have some hardware with has no link to ansible, and the firmware almost none)

2021-01-31 19:57 UTC, capozzid commented
it's been moved into tools folder

2021-02-14 16:45 UTC, jmmourier approved these changes

2021-02-14 16:46 UTC, merged