Add grabber
jmmourier/laughing-couscous pull request #54
Opened 2021-01-27 18:41 UTC by jmmourier

add grabber to the firmware and to hali.
This has been tested on the robot.

2021-01-27 21:53 UTC, devkgs requested changes

2021-01-27 21:53 UTC, devkgs commented on firmware/libraries/Grabber/Grabber.cpp
> +	grabber_state_ = grabberClose;
is it better to rename:
grabberOpen into grabberOpened,
grabberClose into grabberClosed
?

2021-01-27 22:01 UTC, jmmourier commented on firmware/libraries/Grabber/Grabber.cpp
> +	grabber_state_ = grabberClose;
In this case I agree, this come from the software side whe I use this enum for setter and also for getter. 
Thanks, I will fixe it here.

2021-02-01 19:05 UTC, devkgs approved these changes

2021-02-01 20:17 UTC, merged