Create position objects
jmmourier/laughing-couscous pull request #74
Opened 2021-03-19 20:37 UTC by capozzid

2021-03-23 19:01 UTC, jmmourier requested changes
Thanks for the PR. 
it was a quick review from myself, this is moslty architecture discussion regarding 2 points.

2021-03-23 19:01 UTC, jmmourier commented on software/modules/gui/web/src/components/arena/Joystick.tsx
> +const FIX_SEED = 127;
Also I would recommand using moti, I thing it duplicate the code here.

2021-03-24 17:24 UTC, capozzid commented on software/modules/gui/web/src/components/arena/Joystick.tsx
> +const FIX_SEED = 127;
for the commit, yes but it's a small detail I don't think it really matter if this change is part of this commit.
About your second comment, I can't use c++ from a typescript file, one solution would be a json config file but regarding the delay I don't think it is a big issue

2021-03-24 17:29 UTC, capozzid commented on software/modules/utils/include/PositionOrientation.h
> +
I don't see any useful reason to have position as a composition of positionOrientation object (x,y,orientation should be at the same level. However I will change it and make positionOrientation extending position

2021-03-24 18:04 UTC, capozzid commented on software/modules/utils/include/PositionOrientation.h
> +
done

2021-03-25 09:56 UTC, jmmourier commented on software/modules/utils/include/PositionOrientation.h
> +
I really don't think it should be inheritance, it definitly seems composition to me.

2021-03-25 10:00 UTC, capozzid commented on software/modules/utils/include/PositionOrientation.h
> +
I see no advantage of calling position using positionOrientation.position.x_m and calling orientation using simply positionOrientation.orientation_rad

2021-03-25 20:00 UTC, jmmourier approved these changes
We did not agree, but that not blocking.
lets make this works !

2021-03-25 20:40 UTC, devkgs approved these changes

2021-03-25 20:40 UTC, merged