[posi] fix position to absolute between 0 and 2 * PI
jmmourier/laughing-couscous pull request #81
Opened 2021-04-09 15:13 UTC by capozzid

Posi orientation now can only be between 0 and < 6.28318531 (perimeter)

2021-04-09 23:44 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    position_orientation_.orientation_rad_ += delta_orientation;
This does not work if angle is 145*PI
I would recommand using modulo (there is an implementation for float) 
or at least a while instead of an if

2021-04-09 23:46 UTC, jmmourier requested changes

2021-04-09 23:46 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    if (position_orientation_.orientation_rad_ < 0) {
This does not work if angle is 145*PI
I would recommand using modulo (there is an implementation for float)
or at least a while instead of an if

2021-04-09 23:46 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +const float FULL_PERIMETER_RADIAN = M_PI * 2;
WHOLE_ROTATION_RADIAN
full_perimeter seems ambiguous, perimeter is a distance, not an angle, and this is only valid for a radius of 1. Thus I suggest renamming

2021-04-11 09:51 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +    if (position_orientation_.orientation_rad_ < 0) {
a while ? What do you mean by 145*PI ?

2021-04-11 09:51 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +const float FULL_PERIMETER_RADIAN = M_PI * 2;
okay

2021-04-14 10:11 UTC, jmmourier requested changes

2021-04-14 10:11 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
turn_nb can be negative so -2pi will become -4pi then line 84 it will be back to -2pi

2021-04-14 10:12 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
this method shall be
11 pi > 1pi
1 pi > 1pi
-1pi > 1 pi 
-11 pi > 1pi

2021-04-14 10:42 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
no because turn_nb can be negative so if orientation_rad = -5pi = -15.70 then turn_nb will be -2
then formatted_orientation_rad = -15.70 - (-2 * 6.28) = -pi

if(formatted_orientation_rad < 0) then
formatted_orientation_rad = pi

2021-04-14 10:43 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
with your example -2pi formatted_orientation_rad will become 0

2021-04-14 16:12 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
May I recommand using fmod ?
https://www.cplusplus.com/reference/cmath/fmod/

#include <math.h>
float normalization(float angle){
   return fmod(angle, constant::whole_rotation_rad);
}

2021-04-14 16:29 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +    float turn_nb = std::trunc(orientation_rad / constant::whole_rotation_rad);
yes sorry, I did use it yesterday but than changed again, I don't know why. Anyway, it's been pushed with fmod

2021-04-14 22:25 UTC, jmmourier requested changes

2021-04-14 22:25 UTC, jmmourier commented on software/modules/posi/src/Posi.cpp
> +    if (formatted_orientation_rad < 0) {
I think This is not needed because fmod do it already

2021-04-19 10:32 UTC, capozzid commented on software/modules/posi/src/Posi.cpp
> +    if (formatted_orientation_rad < 0) {
nop it does not, if orientation_rad = 5pi then without IF the result will be -pi where we want pi

2021-04-28 18:50 UTC, devkgs approved these changes

2021-04-28 18:50 UTC, jmmourier approved these changes

2021-04-28 18:50 UTC, merged